### ISSUE TITLE
.bayern is missing

### ISSUE THREAD

**Issue by vitushoesl** [HelgeSverre/Domain-Availability#12]
Hi,

I'm using your script for a few weeks now but theres one new tld missing - that's .bayern. It would be cool if you may add it.

Best regards
Vitus

**Comment by HelgeSverre** [comment]
Done
https://github.com/HelgeSverre/Domain-Availability/commit/1481903dcc8c7ae12b54e8cbfb2ede9f87e79cc5

**Comment by vitushoesl** [comment]
Thank you so much :)

**Comment by HelgeSverre** [comment]
You're welcome, let me know if you run into any issues.
