### ISSUE TITLE
'./vendor/ folder is missing

### ISSUE THREAD

**Issue by malato** [HelgeSverre/Domain-Availability#19]
I've tried to test the script, but I've got a Fatal error: 

require(): Failed opening required './vendor/autoload.php' (include_path='.:/usr/local/pear/php54') in example.php on line 9

Can you tell me why it's missing?

**Comment by WilliamPearce** [comment]
The folder named vendor is part of the Composer infrastructure, which should be used to install **domain-availability**. See the notes. Get to know Composer, it's quite straightforward and extremely useful when you've got to grips with the way it works.

**Comment by HelgeSverre** [comment]
Pretty much what WilliamPearce said.

To use Domain Availability you need to use Composer to pull in the dependencies for it.

You can find a pretty good tutorial on how to use Composer on TutsPlus: http://code.tutsplus.com/tutorials/easy-package-management-with-composer--net-25530
