### ISSUE TITLE
Showing available domain as unavailable

### ISSUE THREAD

**Issue by LukeeB** [HelgeSverre/Domain-Availability#20]
Today I did just a small test. First, I tried to find a domain that for sure is available. So I visited the official Verisign page (http://www.verisign.com/en_US/domain-names/index.xhtml) and inserted a domain name "sjekruze.com" (I just wanted some nonsense word for the test purpose). See the Screenshot attached:
![verisign-test](https://cloud.githubusercontent.com/assets/1163604/11527657/926ac58a-98e2-11e5-8df8-05cc29aaf799.jpg)
Next, I went to your Ajax Call example, edited the domain variable to "sjekruze.com" - here: http://jsfiddle.net/cs8t1jgf/4/ but the result is "sjekruze.com is not available or invalid". So, my first test failed. So please, can you confirm that the code is basically working? Maybe there is a small problem somewhere that I do not see...anyways, this script is very useful and thank you for your time making this.

**Comment by HelgeSverre** [comment]
My apologies, I have not updated those snippets, the API has changed slightly, it now respons with 

```
{
status: "AVAILABLE",
domain: "sjekruze.com"
}
```

I will udpate the JSFiddle snippets

**Comment by HelgeSverre** [comment]
The snippets are now udated.
