### ISSUE TITLE
on searching .co.uk or co.in getting error

### ISSUE THREAD

**Issue by ranasoyab** [HelgeSverre/Domain-Availability#21]
Fatal error: Uncaught exception 'Exception' with message 'No WHOIS entry was found for that TLD' in /var/www/html/api/domain/src/Service/DomainAvailability.php:50

I tried to add co.uk or co.in servers to src/data/servers.json then error message is comming WHOIS query failed

Please help.

**Comment by ranasoyab** [comment]
http://mxr.mozilla.org/mozilla-central/source/netwerk/dns/effective_tld_names.dat?raw=1

List of all TLD's

**Comment by WilliamPearce** [comment]
ranasoyab

add the following as entries in src/data/servers.json

    "co.uk": {
      "server": "whois.nic.uk",
      "not_found": "This domain name has not been registered."
    },    
    "co.in": {
      "server": "whois.inregistry.net",
      "not_found": "NOT FOUND"
    },

Happy New Year

Bill

**Comment by ranasoyab** [comment]
Thanks can you let me how you found this servers. Please

**Comment by WilliamPearce** [comment]
From https://publicsuffix.org/list/effective_tld_names.dat **.co.uk** is from the same registry (Nominet) as **.uk**, which is already in servers.json. Same with **.co.in** which has the same registry as **.in**. Others may not be so easy to find.

**Comment by ranasoyab** [comment]
Thank you very much :)

**Comment by HelgeSverre** [comment]
@WilliamPearce would you mind creating a PR with the fix? :)

**Comment by LadyDeathKZN** [comment]
Hi there, I am from South Africa. I am building a domains website, and found your script. Other scripts I have used do not work the right way or give the results as I have hoped.

I have added this to the array of domains:
"co.za" => array("whois.registry.net.za", "Available "),

and this to the server.json:
"co.za": {
    "server": "whois.registry.net.za",
    "not_found": "Available "
  },

Even with other Whois server information I am unable to find the TLD

I have gotten the information from here:
https://publicsuffix.org/list/effective_tld_names.dat

// za : http://www.zadna.org.za/content/page/domain-information

https://www.registry.net.za/content.php?wiki=1&contentid=59&title=WHOIS%20Services

But either way I am met with the error:
Fatal error: Uncaught Exception: WHOIS server not found for that TLD

Do you have any suggestions or ideas to what I may be doing wrong.
