### ISSUE TITLE
Run without composer?

### ISSUE THREAD

**Issue by howardhee** [HelgeSverre/Domain-Availability#23]
Hi, I want to integrate your code to my current project and deploy to remote server. Possible I integrate without this line of code? Thanks

require './vendor/autoload.php';

**Comment by HelgeSverre** [comment]
No.

**Comment by mellat** [comment]
You mean , there is noway to run the code without composer?

**Comment by HelgeSverre** [comment]
There is, but, why don't you want to use Composer?

**Comment by mellat** [comment]
Because , our server don't let us to run Shell on our host :|

**Comment by HelgeSverre** [comment]
You don't need to run it on the host, you can prepare it locally and then transfer all the files composer downloaded to your server.

**Comment by mellat** [comment]
aha , But there is our problem , we do not know how to do this , Your script is really great but I think it will be great if you put some article in your blog about how to install and use "HelgeSverre/Domain-Availability" in your host . and all of this is just suggestion ... Thank you mr helge

**Comment by HelgeSverre** [comment]
the way composer works is by looking into a json file and download the dependancies, in this script there is only one dependancy and that is this package: https://packagist.org/packages/jeremykendall/php-domain-parser

To install composer you go to https://getcomposer.org/ and read the "Getting started" part.

When you have installed composer (and injected it into your PATH environment variable if you are on windows) you can write ```composer require helgesverre/domain-availability``` this will create a vendor/ folder, all you really need to do is to take that folder and upload it to your project and require the vendor/autoload.php file into whatever script is going to be using the domain availability script.
