### ISSUE TITLE
No WHOIS entry was found for that TLD 

### ISSUE THREAD

**Issue by JD719** [HelgeSverre/Domain-Availability#25]
Hi, I'm using example.php and it doesn't matter what domain I try, always get the same output:

> No WHOIS entry was found for that TLD 

What's wrong?

**Comment by HelgeSverre** [comment]
The path to the servers.json file is most likely wrong, double check if it is correct.

**Comment by JD719** [comment]
You are right thank you!

**Comment by HelgeSverre** [comment]
Goodie :)
