### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by sunbarve** [HelgeSverre/Domain-Availability#27]
( ! ) Fatal error: Call to undefined function Pdp\idn_to_ascii() in C:\wamp\www\Domain-Availability-master\vendor\jeremykendall\php-domain-parser\src\Pdp\Parser.php on line 319
Call Stack
#	Time	Memory	Function	Location
1	0.0004	251176	{main}( )	..\example.php:0
2	0.0094	645272	Helge\Service\DomainAvailability->isAvailable( )	..\example.php:35
3	0.0094	645424	Helge\Service\DomainAvailability->parse( )	..\DomainAvailability.php:47
4	0.0228	2459456	Pdp\Parser->isSuffixValid( )	..\DomainAvailability.php:99
5	0.0228	2459608	Pdp\Parser->getRawPublicSuffix( )	..\Parser.php:245
6	0.0228	2459688	Pdp\Parser->normalize( )	..\Parser.php:154

**Comment by HelgeSverre** [comment]
From the readme:

## Notes

If you are getting the error:
```
Fatal error: Call to undefined function Pdp\idn_to_ascii()
```
Be sure to enable the php extension called ```intl``` as the domain parsing extension requires it!

**Comment by sunbarve** [comment]
but where to change php extension intl as domain parsing extension
