### ISSUE TITLE
this code can't use.

### ISSUE THREAD

**Issue by heyokdang** [HelgeSverre/Domain-Availability#29]
This is stupid code, i have downloaded and put in my server but example can't run.

**Comment by HelgeSverre** [comment]
Then you are doing it wrong.



On Sun, Jan 01, 2017 at 9:14am, Lighthouse Nguyen < notifications@github.com [notifications@github.com] > wrote:
This is stupid code, i have downloaded and put in my server but example can't run.

**Comment by heyokdang** [comment]
Hi Hero,

i'm very sorry for that message, but i really met problems with your code, can't use.

this is my problems i met:
1) go to here
http://localhost/domain-availability-master/example.php

this is the error:
Fatal error: Class 'Helge\Client\SimpleWhoisClient' not found in E:\xampp\htdocs\domain-availability-master\example.php on line 15

2) http://localhost/domain-availability-master/mytest.php
this is the code of mytest.php
<?php
define('ROOTPATH', __DIR__);
include (ROOTPATH.'\src\Service\DomainAvailability.php');
$Domain = new DomainAvailability;
$available = $Domain->is_available("helgesverre.com");

if ($available) {
    echo "The domain is not registered";
} else {
    echo "The domain is registered";
}

go to here http://localhost/domain-availability-master/mytest.php i see the error.

Fatal error: Class 'DomainAvailability' not found in E:\xampp\htdocs\domain-availability-master\mytest.php on line 4

**Comment by HelgeSverre** [comment]
Are you using composer?



On Sun, Jan 01, 2017 at 3:28pm, Lighthouse Nguyen < notifications@github.com [notifications@github.com] > wrote:
Hi Hero,

i'm very sorry for that message, but i really met problems with your code, can't use.

this is my problems i met:

 1. go to here
    http://localhost/domain-availability-master/example.php [http://localhost/domain-availability-master/example.php]

this is the error:
Fatal error: Class 'Helge\Client\SimpleWhoisClient' not found in E:\xampp\htdocs\domain-availability-master\example.php on line 15

 1. http://localhost/domain-availability-master/mytest.php [http://localhost/domain-availability-master/mytest.php]
    this is the code of mytest.php

is_available("helgesverre.com"); if ($available) { echo "The domain is not registered"; } else { echo "The domain is registered"; } go to here http://localhost/domain-availability-master/mytest.php i see the error. Fatal error: Class 'DomainAvailability' not found in E:\xampp\htdocs\domain-availability-master\mytest.php on line 4—

**Comment by heyokdang** [comment]
Hi Hero, 

Please refresh page to see my message, edited.

I'm a web developer. I'm using LAMP, i'm good with LAMP.

**Comment by HelgeSverre** [comment]
You need to use composer.



On Sun, Jan 01, 2017 at 3:34pm, Lighthouse Nguyen < notifications@github.com [notifications@github.com] > wrote:
Hi Hero,

Please refresh page to see my message, edited.

I'm a web developer. I'm using LAMP, i'm good with LAMP.

**Comment by heyokdang** [comment]
I have installed with composer, "php composer update", example.php is running good now, but now i'm not sure how can i move this code to my project, it is a form. My project is only a simple php project, not using composer. Please give me your advice.

Thank you very much.

**Comment by HelgeSverre** [comment]
Require the domainavailability file into your php file



On Sun, Jan 01, 2017 at 5:55pm, Lighthouse Nguyen < notifications@github.com [notifications@github.com] > wrote:
I have installed with composer, "php composer update", example.php is running good now, but now i'm not sure how can i move this code to my project, it is a form. My project is only a simple php project, not using composer. Please give me your advice.

Thank you very much.
