### ISSUE TITLE
Bug in get_tld function

### ISSUE THREAD

**Issue by adamhesim** [HelgeSverre/Domain-Availability#3]
Hi,
I think your count test in get_tld function is not right : 
You use the explode function with '.' as delimiter then check 
`if(count($split) === 0)`
but even if there is no '.' in the domain name, explode will return a 1 element array with the whole incorrect string in it.
So get_tld('foo') will not throw the expected exception. I think this test solves it : 
`if(count($split) < 2 )`

[explode documentation](http://fr2.php.net/manual/en/function.explode.php) : _If delimiter contains a value that is not contained in string and a negative limit is used, then an empty array will be returned, otherwise an array containing string will be returned._

By the way, thank you for this so usefull class.

**Comment by rufinus** [comment]
fixed by #5
