### ISSUE TITLE
TLD not found

### ISSUE THREAD

**Issue by norhanelnezamy** [HelgeSverre/Domain-Availability#31]
I follow your usage steps but i found this exception No WHOIS entry was found for that TLD

**Comment by NathanHeffley** [comment]
Could you please explain what domain you tried searching for?

**Comment by norhanelnezamy** [comment]
I'm searching for domain like this domain.com.sa or domain.co.uk

**Comment by Jerome1337** [comment]
I get the same error with all domains with `co.uk` tld, when I try another tld I get the valid result

**Comment by HelgeSverre** [comment]
Not 100% sure, but I believe you might have to add "co.uk" and "com.sa" as their own entry within the servers.json file for those to work.

**Comment by Jerome1337** [comment]
@HelgeSverre I tested `co.uk` tld right now on using the master branch and it work great and I found why tld like `co.uk` or `com.sa` are not working right now.

The lastest release tag you made is `0.2.2` but this tag include an old version of your `server.json`. Just re-create a new release tag (`0.2.3` or `0.3` if there is BC break changes) to fix this problem.

**Comment by LadyDeathKZN** [comment]
Gosh okay, I forgot where I had posted. I need some help adding .co.za
I have added the array and the server.json info

I have gotten the information from here:
https://www.iana.org/whois?q=co.za

but I still get an error that it could not be found

Any help would be great :)

**Comment by privyreza** [comment]
Get error even with the .com domain:, here is the tinker code:

```
>>> use Helge\Loader\JsonLoader;
>>> use Helge\Client\SimpleWhoisClient;
>>> use Helge\Service\DomainAvailability;
>>> $whoisClient = new SimpleWhoisClient();
=> Helge\Client\SimpleWhoisClient {#4764}
>>> $dataLoader = new JsonLoader("src/data/servers.json");
=> Helge\Loader\JsonLoader {#4775}
>>> $service = new DomainAvailability($whoisClient, $dataLoader);
=> Helge\Service\DomainAvailability {#4778}
>>> $service->isAvailable("helgesverre.com")
Exception with message 'No WHOIS entry was found for that TLD'
```
