### ISSUE TITLE
Fatal error: Call to undefined function Pdp\idn_to_ascii()

### ISSUE THREAD

**Issue by shqawe1** [HelgeSverre/Domain-Availability#37]
Hi Helge,

i got this error : 
Fatal error: Call to undefined function Pdp\idn_to_ascii()

can you help me with this please?

**Comment by HelgeSverre** [comment]
The PHP Module/extension intl is required.

https://www.google.com/search?q=how+to+isntall+intl+php

**Comment by shqawe1** [comment]
i install extension but i got this error 
idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated

my PHP version is 7.2

**Comment by shqawe1** [comment]
i solve this problem by editing Parser.php file on this path 
vendor\jeremykendall\php-domain-parser\src\Pdp\Parser.php

you should to change the code in line 318 
From:
`$part = idn_to_ascii($part);`
To:
`$part = idn_to_ascii($part,0,INTL_IDNA_VARIANT_UTS46);`

and change the code in line 336:
From:
`$part = idn_to_utf8($part);`
To:
`$part = idn_to_utf8($part,0,INTL_IDNA_VARIANT_UTS46);`

and it will work with php 7.2

Thanks Helge.

**Comment by atefBB** [comment]
Why not converting this issue to a PR?

**Comment by HelgeSverre** [comment]
@shqawe1  would you mind creating a PR?
