### ISSUE TITLE
Invalid .IN WHOIS Server

### ISSUE THREAD

**Issue by chinmay241** [HelgeSverre/Domain-Availability#61]
I noticed the servers.json is using the old WHOIS Server for .IN TLDs which don't operate anymore. This needs a update as well as adding support for newer 2nd Level .IN Domains

- [x] .IN
- [x] CO.IN
- [x] NET.IN
- [x] FIRM.IN
- [x] GEN.IN
- [x] ORG.IN

**Comment by HelgeSverre** [comment]
Do you know which new whois server to use for these 2nd level domains?

**Comment by chinmay241** [comment]
> 
> 
> Do you know which new whois server to use for these 2nd level domains?

**Comment by chinmay241** [comment]
I have created a pull request with these updates, sorry for the incomplete message. Thought to create a issue then prepare the Pull Request.

**Comment by HelgeSverre** [comment]
Merged, and released as new version.
