### ISSUE TITLE
Whois for .dj

### ISSUE THREAD

**Issue by uruloke** [HelgeSverre/Domain-Availability#7]
Here is the WhoIs for .DJ
http://www.nic.dj/whois.php
Should be simple to implement, its just a get array that looks like this
http://www.nic.dj/whois3.php?domaine={domainname}

**Comment by HelgeSverre** [comment]
This script connects directly to the underlying whois servers that these kinds of sites use, I am not willing to go out, parse and maintain a web scraper for thousand of different websites like this, if the whois server is not public or unknown, the domain will not be supported.
