### ISSUE TITLE
require('vendor/autoload.php');  is unknown  in my system

### ISSUE THREAD

**Issue by logindian** [HelgeSverre/Domain-Availability#8]
In the example, it is calling require('vendor/autoload.php');
I dont have any such files in my system and so it throws error.

**Comment by HelgeSverre** [comment]
You have to run composer in your projects directory.
Or manually download the AvailabilityService.php file and include that
On Fri, Feb 06, 2015 at 5:16 AM, Logan <notifications@github.com> wrote:In the example, it is calling require('vendor/autoload.php');
I dont have any such files in my system and so it throws error.

**Comment by logindian** [comment]
I installed it manually.. But I could not vendor folder.. Shall I remove
following code to run example ?
 require('vendor/autoload.php');

Thanks & Regards,
Loganathan

**Comment by HelgeSverre** [comment]
if you installed it manually you should noy include the vendor/autoload line, but rather ``` require()``` the fike you downloaded.
On Fri, Feb 06, 2015 at 11:06 AM, Logan <notifications@github.com> wrote:I installed it manually.. But I could not vendor folder.. Shall I remove
following code to run example ?
 require('vendor/autoload.php');

Thanks & Regards,
Loganathan

**Comment by HelgeSverre** [comment]
if you installed it manually you should not include the vendor/autoload line, but rather ```require()``` the file you downloaded

**Comment by logindian** [comment]
So I shall include following ?

Require(AvailabilityService.php)

Thanks & Regards,
Loganathan

**Comment by HelgeSverre** [comment]
```php
require("AvailabilityService.php");
```

Should be correct, but specify the proper path qhere you placed the file, i usually place my library and script files in a directory called /libs, but you might have a different practice.

**Comment by HelgeSverre** [comment]
Closing this since I have not heard back since February...
